// Maintainer helper: node web/generate-policy.mjs > web/unicode-policy.mjs
// Validation: node web/generate-policy.mjs --check
import { readFile } from "node:fs/promises";

const source = new URL("../src/dewatermark/unicode_policy.json", import.meta.url);
const policy = JSON.parse(await readFile(source, "utf8"));
const rows = policy.rules.map((rule) => {
  const values = [
    `0x${rule.start.toLowerCase()}`,
    `0x${rule.end.toLowerCase()}`,
    JSON.stringify(rule.category),
    JSON.stringify(rule.action),
    JSON.stringify(rule.token),
    JSON.stringify(rule.safe),
  ];
  return `  [${values.join(", ")}],`;
});
const generated = [
  "// Generated from ../src/dewatermark/unicode_policy.json by generate-policy.mjs.",
  "// Do not edit this file directly.",
  `export const POLICY_VERSION = ${JSON.stringify(policy.policy_version)};`,
  "",
  "export const POLICY_RULES = Object.freeze([",
  ...rows,
  "]);",
  "",
].join("\n");

if (process.argv.includes("--check")) {
  const target = new URL("./unicode-policy.mjs", import.meta.url);
  const current = await readFile(target, "utf8");
  if (current !== generated) {
    process.stderr.write(
      "web/unicode-policy.mjs is stale; regenerate it from the canonical policy.\n",
    );
    process.exitCode = 1;
  }
} else {
  process.stdout.write(generated);
}
